### ISSUE TITLE
File problem

### ISSUE THREAD

**Issue by Lihongjian520** [alexandrosstergiou/Inception_v3_TV_Human_Interactions#1]
Thank you very much for the code. Where is  ' weights.best.hdf5' file??????

**Comment by alexandrosstergiou** [comment]
You should run the `inceptionv3_highfive_train.py` file first to train the model. This will store the weights in an `HDF5` file which you can then use for the visualisations.

Best,

**Comment by Lihongjian520** [comment]
1. Why do I run this program, I find that I need to download this 'inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5' file,
2. Run this program and it will automatically generate 'weights. Best. Hdf5' file??? Right?

**Comment by alexandrosstergiou** [comment]
Your first problem is related to loading the Inception Imagenet weights solely for the classifier (does not correspond to issues in this repository, you can have a look at fchollet's -now deprecated- [repo](https://github.com/fchollet/deep-learning-models)). Yes, as in the previous comment, the TL model's weights will be saved to `weights.best.hdf5` after training.

Best.

**Comment by Lihongjian520** [comment]
I still can't solve my first problem
Thank you

**Comment by alexandrosstergiou** [comment]
I can only suggest to download your missing weights from the releases page in the [Keras model repo](https://github.com/fchollet/deep-learning-models/releases). I will be closing this issue since it is not associated to this repo.

**Comment by Lihongjian520** [comment]
I downloaded it, but I don't know where it is, or it's not in the right place for other reasons
